apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-secrets-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template: 
    metadata: 
      labels:
        app: helloworld
    spec:
      containers:
      - name: secrets-containers
        image: krutika1052/hello_node
        ports:
        - name: nodejs-port
          containerPort: 8081
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret: 
          secretName: db-secrets



    
